cache:
  paths:
    - node_modules/

image: node:16.3-buster-slim

variables:
  GIT_DEPTH: 1

gatsby-build:
  only: # Only run for these branches
  - develop
  - main
  - gitlab-debug

  stage: build

  tags:
  - docker

  before_script:
  - apt-get update && apt-get install -y git
  - yarn install
  - ./prebuild.sh full # fetch content repo

  script:
  - ./node_modules/.bin/gatsby build

  artifacts:  # Use by GitLab pages
    paths:
    - public
