cache:
  paths:
    - node_modules/

image: node:16.3-buster-slim

pages:
  only:
    - develop  # Only run for this branch
 
  before_script:
    - apt-get update && apt install -y git
    - yarn install

  script:
    - ./prebuild.sh full # fetch content repo
    - ./node_modules/.bin/gatsby build

  artifacts:  # Use by GitLab pages
    paths:
      - public