cache:
  paths:
    - node_modules/

image: node:16.3-buster-slim

variables:
  GIT_DEPTH: 1

prebuild:
  stage: .pre
  only:
  - develop
  - main
  - gitlab-debug

  script:
  - apt-get update && apt-get install -y --no-install-recommends git
  - yarn install
  - ./prebuild.sh full # fetch content repo

gatsby-build:
  stage: build
  only: # Only run for this branch
  - develop
  - main
  - gitlab-debug
 
  script:
  - ./node_modules/.bin/gatsby build

  artifacts:  # Use by GitLab pages
    paths:
    - public
