cache:
  paths:
    - node_modules/
    - .cache
    - public

image: registry.gitlab.com/openbeta/openbeta-nodejs-docker:16.3

variables:
  GIT_DEPTH: 1
  DOCKER_DRIVER: overlay2

gatsby-build:
  stage: build

  tags:
  - docker

  before_script:
  - git show --summary
  - if [ "$FORCE_CLEAN" == "true" ]; then rm -rf node_modules; fi;
  - yarn install --no-progress
  - if [ "$FORCE_CLEAN" == "true" ]; then ./node_modules/.bin/gatsby clean; fi;
  - ./prebuild.sh # fetch content repo

  script:
  - ./node_modules/.bin/gatsby build

# Job name must be 'pages' in order for GitLab to deploy to static site
pages:
  stage: build
  tags:
    - docker
  needs: [gatsby-build]
  only: # Only run for these branches
  - develop
  - main

  script:
    - ls -la public # Dummy command as required by Gitlab linter
  artifacts:  # Use by GitLab pages
    paths:
    - public
