cache:
  paths:
    - node_modules/
    - .cache
    - public

image: node:16.3-buster-slim

variables:
  GIT_DEPTH: 1
  DOCKER_DRIVER: overlay2

# Job name must be 'pages' in order for GitLab to deploy to static site
pages:
  only: # Only run for these branches
  - develop
  - main
  - gitlab-debug

  stage: build

  tags:
  - docker

  before_script:
  - apt-get update && apt-get install -y git
  - yarn install --no-progress
  - ./prebuild.sh full # fetch content repo

  script:
  - ./node_modules/.bin/gatsby build

  artifacts:  # Use by GitLab pages
    paths:
    - public
