cache:
  paths:
    - node_modules/
    - .cache
    - public

image: registry.gitlab.com/openbeta/openbeta-nodejs-docker:16.3

variables:
  GIT_DEPTH: 1
  DOCKER_DRIVER: overlay2

# Job name must be 'pages' in order for GitLab to deploy to static site
# NOTE: Rename job and comment out branch restriction to test build time
test-pages:
#  only: # Only run for these branches
#  - develop
#  - main
#  - gitlab-debug

  stage: build

  tags:
  - docker

  before_script:
  - yarn install --no-progress
  - ./prebuild.sh full # fetch content repo

  script:
  - ./node_modules/.bin/gatsby build

  artifacts:  # Use by GitLab pages
    paths:
    - public
