cache:
  paths:
    - node_modules/

image: node:16.3-buster-slim

pages:
  before_script:
    - apt-get update && apt install -y git
    - yarn install

  script:
    - ./prebuild.sh full # fetch content repo
    - ./node_modules/.bin/gatsby build

  artifacts:
    paths:
      - public