version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: openbeta/opentacos-dev:latest
    container_name: opentacos-dev-latest
    volumes:
      - ./.cache:/app/.cache
      - ./node_modules:/app/node_modules
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: curl --fail http://web:3000 || exit 1
      interval: 1m
      retries: 30
      start_period: 2m
      timeout: 5m
