version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: openbeta/opentacos-dev:latest
    container_name: opentacos-dev-latest
    volumes:
      - ./.cache:/app/.cache
      - ./node_modules:/app/node_modules
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
