[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install --no-progress --silence"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = 'production'
DEPLOYMENT_ENV = 'railway'
NODE_OPTIONS = "--max-old-space-size=512"
