import './global.css'
import Header from './header'
import Footer from './footer'
import { NextAuthProvider } from './components/NextAuthProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): any {
  return (
    <html lang='en'>
      <body className='mx-auto'>
        <NextAuthProvider>
          <Header />
        </NextAuthProvider>
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
