on:
  push:
    branches:
      - develop

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror develop branch to staging branch
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: develop
        dest: staging
