name: 'tests'

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: "Preview"
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn install --no-progress

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test-all
        env:
          SIRV_CLIENT_SECRET_RO: ${{ secrets.SIRV_CLIENT_SECRET_RO }}

      - name: Test build
        run: yarn build
        env:
          SIRV_CLIENT_SECRET_RO: ${{ secrets.SIRV_CLIENT_SECRET_RO }}

  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build the stack
        run: docker-compose up -d
        env:
          SIRV_CLIENT_SECRET_RO: ${{ secrets.SIRV_CLIENT_SECRET_RO }}
      - name: Wait for server
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3000/'
          responseCode: 200
          timeout: 300000
          interval: 2000
      - name: Show server log
        run: docker logs --tail 10 opentacos-dev-latest
      - name: Ping home page
        run: docker run --network container:opentacos-dev-latest appropriate/curl -L -s --retry 10 --retry-connrefused http://localhost:3000/
