name: 'Continuous integration'

on: [push, pull_request]

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          paths_ignore: '["**/README.md"]'
          concurrent_skipping: 'same_content_newer'


  build:
    name: Test build
    runs-on: ubuntu-22.04
    environment: "Preview"
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '20'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn install --no-progress

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test
        if: ${{ github.event_name == 'pull_request' }}

      - name: Build project
        run: yarn build
        if: ${{ github.event_name != 'pull_request' }}

  # build docker image and push to registry
  docker:
    runs-on: ubuntu-22.04
    needs: build
    environment: production
    steps:
      - name: 'Checkout Project'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Pull Docker image
        run: |
          docker pull vnguyen/open-tacos:latest || true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            vnguyen/open-tacos
          tags: |
            type=ref,event=branch
            type=semver,pattern={{raw}}
            type=sha,format=long

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            AUTH0_CLIENT_SECRET=${{ vars.AUTH0_CLIENT_SECRET }}
            AUTH0_DOMAIN=${{ vars.AUTH0_DOMAIN }}
            AUTH0_CLIENT_ID=${{ vars.AUTH0_CLIENT_ID }}
            AUTH0_MGMT_CLIENT_ID=${{ vars.AUTH0_MGMT_CLIENT_ID }}
            AUTH0_MGMT_CLIENT_AUDIENCE=${{ vars.AUTH0_MGMT_CLIENT_AUDIENCE }}
            AUTH0_MGMT_CLIENT_SECRET=${{ vars.AUTH0_MGMT_CLIENT_SECRET }}
            MOBILE_AUTH_SECRET=${{ vars.MOBILE_AUTH_SECRET }}
            GC_BUCKET_CLIENT_EMAIL=${{ vars.GC_BUCKET_CLIENT_EMAIL }}
            GC_BUCKET_PRIVATE_KEY=${{ vars.GC_BUCKET_PRIVATE_KEY }}
            GC_BUCKET_NAME=${{ vars.GC_BUCKET_NAME }}
            NEXT_PUBLIC_MAPBOX_API_KEY=${{ vars.NEXT_PUBLIC_MAPBOX_API_KEY }}
            NEXT_PUBLIC_CDN_URL=${{ vars.NEXT_PUBLIC_CDN_URL }}
            NEXTAUTH_SECRET=${{ vars.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_API_SERVER=${{ vars.NEXT_PUBLIC_API_SERVER }}
            NEXT_TELEMETRY_DISABLED: 1
            NEXT_PUBLIC_DEVTOOLS_ENABLED: 0
            OPENBETA_API_SERVER=${{ vars.NEXT_PUBLIC_API_SERVER }}
