name: 'tests'

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn install --no-progress

      - name: Lint code
        run: yarn lint

      - name: Copy a subset of content files
        run: ./prebuild.sh

      - name: Test build
        run: yarn build
