name: 'tests'

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: "Preview"
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn install --no-progress

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test-all
        env:
          SIRV_CLIENT_SECRET_RO: ${{ secrets.SIRV_CLIENT_SECRET_RO }}

      - name: Test build
        run: yarn build
        env:
          SIRV_CLIENT_SECRET_RO: ${{ secrets.SIRV_CLIENT_SECRET_RO }}
  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build the stack
        run: docker-compose up -d
        env:
          SIRV_CLIENT_SECRET_RO: ${{ secrets.SIRV_CLIENT_SECRET_RO }}
      - name: Test docker-compose up
        run: docker run --network container:opentacos-dev-latest appropriate/curl -s --retry 20 --retry-connrefused http://localhost:3000/
